### 0. 安裝PyTorch

In [6]:
import sys
!{sys.executable} -m pip install torch==1.3.0 torchvision==0.4.1 -f https://download.pytorch.org/whl/torch_stable.html

Looking in links: https://download.pytorch.org/whl/torch_stable.html
You should consider upgrading via the 'pip install --upgrade pip' command.


### 1. 檢查PyTorch版本

In [2]:
import torch
print(torch.__version__)

1.2.0


## PyTorch 張量 (Tensor)

In [3]:
##匯入函式庫，numpy會是建立PyTorch張量的好幫手
import torch
import numpy as np

### 3. 用PyTorch生成張量

In [10]:
x = torch.rand(2, 3)
x

tensor([[0.9169, 0.2939, 0.4052],
        [0.6541, 0.9992, 0.1776]])

In [11]:
##兩種不同「查看維度屬性」的方法
print(x.shape)
print(x.size())

torch.Size([2, 3])
torch.Size([2, 3])


###### 複習：
第零階張量-純量 <br /> 
第一階張量-向量<br /> 
第二階張量-矩陣<br /> 
第三階以上張量-張量<br /> 

In [12]:
##試著生成多階張量吧！
y=torch.rand(2,3,4,5)
print(y.size())
y

torch.Size([2, 3, 4, 5])


tensor([[[[0.8373, 0.2489, 0.9917, 0.7144, 0.5369],
          [0.8290, 0.0578, 0.6364, 0.5963, 0.7052],
          [0.7528, 0.3740, 0.6362, 0.4220, 0.7085],
          [0.6688, 0.7499, 0.1913, 0.7012, 0.2168]],

         [[0.3086, 0.0961, 0.0876, 0.6543, 0.7420],
          [0.8526, 0.4401, 0.4274, 0.4589, 0.2411],
          [0.8111, 0.3577, 0.3171, 0.4587, 0.8622],
          [0.5898, 0.3102, 0.2402, 0.9610, 0.7940]],

         [[0.6125, 0.0651, 0.0229, 0.3110, 0.7513],
          [0.3354, 0.5185, 0.4780, 0.6855, 0.3955],
          [0.7821, 0.9251, 0.4345, 0.1571, 0.0756],
          [0.3716, 0.1517, 0.2056, 0.3312, 0.2461]]],


        [[[0.9512, 0.3765, 0.8852, 0.4113, 0.2392],
          [0.3525, 0.2704, 0.5454, 0.0528, 0.6720],
          [0.5275, 0.7955, 0.9013, 0.5544, 0.1854],
          [0.2510, 0.7392, 0.8731, 0.3520, 0.3498]],

         [[0.9712, 0.4956, 0.5836, 0.1200, 0.6978],
          [0.9885, 0.4170, 0.2495, 0.3541, 0.1924],
          [0.0605, 0.9447, 0.1575, 0.0846, 0.8739],
  

In [4]:
#純量
scalar =torch.tensor(3.141592)
print(scalar)
print(scalar.size())
print(scalar.item())

tensor(3.1416)
torch.Size([])
3.141592025756836


### 4. 基本數據類型

32位元浮點數：torch.FloatTensor (default)<br /> 
64位元浮點數：torch.DoubleTensor<br /> 
16位元整數：torch.ShortTensor<br /> 
32位元整數：torch.IntTensor<br /> 
64位元整數：torch.LongTensor<br /> 
char：torch.int8<br /> 
btye：torch.uint8<br /> 

In [29]:
tensor = torch.tensor([3.141592]) 
long_t=tensor.long()
print(" - long - ")
print(long_t)
half_t=tensor.half()
print("\n - half - ")
print(half_t)
int_t=tensor.int()
print("\n - int - ")
print(int_t)
float_t=tensor.float()
print("\n - float - ")
print(float_t)
short_t=tensor.short()
print("\n - short - ")
print(short_t)
char_t=tensor.char()
print("\n - char - ")
print(char_t)
byte_t=tensor.byte()
print("\n - byte - ")
print(byte_t)

 - long - 
tensor([3])

 - half - 
tensor([3.1406], dtype=torch.float16)

 - int - 
tensor([3], dtype=torch.int32)

 - float - 
tensor([3.1416])

 - short - 
tensor([3], dtype=torch.int16)

 - char - 
tensor([3], dtype=torch.int8)

 - byte - 
tensor([3], dtype=torch.uint8)


### 5. tensor與Numpy中的ndarray互相轉換

In [6]:
##tensor to ndarray
a = torch.randn((3, 2))
print(a)
numpy_a = a.numpy()
print(numpy_a)

tensor([[ 1.3716, -0.6831],
        [ 0.3051, -0.2912],
        [-1.6451, -1.9067]])
[[ 1.371623   -0.6830888 ]
 [ 0.30512834 -0.29123798]
 [-1.6451058  -1.9067299 ]]


In [7]:
## ndarray to tensor
torch_a = torch.from_numpy(numpy_a)
torch_a

tensor([[ 1.3716, -0.6831],
        [ 0.3051, -0.2912],
        [-1.6451, -1.9067]])

### 注意：
tensor和ndarray共享記憶體，兩者之間的轉換很快，幾乎不會消耗什麼資源。<br />
如果其中一個改變，另外一個也會隨之改變。

In [8]:
b = torch.randn((3, 2))
torch_a.add_(b)
#torch_a=torch_a+b
print(torch_a)
print(numpy_a)

tensor([[ 0.1771,  0.0649],
        [-0.0519, -0.5028],
        [-2.2636, -0.3999]])
[[ 0.17706525  0.06488007]
 [-0.05190542 -0.50282264]
 [-2.2635949  -0.3998803 ]]


### 6. 不同的張量初始化方法

In [35]:
## 隨機
rand_t = torch.rand(4, 4)
print(rand_t)

tensor([[0.7649, 0.7091, 0.8841, 0.8805],
        [0.2049, 0.2878, 0.8374, 0.0596],
        [0.7334, 0.0678, 0.8426, 0.1292],
        [0.8830, 0.0414, 0.0194, 0.2495]])


In [40]:
## 全部填一
ones_t = torch.ones(4, 4)
print(ones_t)

## 改變類型
ones_t_new = torch.ones(4, 4,dtype=torch.long)
print(ones_t_new)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])


In [10]:
## 全部填零
zeros_t=torch.zeros(4,4)
#zeros_t=torch.empty(4,4)
print(zeros_t)

tensor([[7.8363e+17, 2.0190e-19, 1.3563e-19, 4.5071e+16],
        [1.4584e-19, 1.4584e-19, 1.4584e-19, 3.1432e-12],
        [1.3589e-19, 1.3563e-19, 7.9717e-10, 5.8270e-10],
        [5.8270e-10, 5.8270e-10, 4.9153e-14, 1.3494e+37]])


In [12]:
## 產生單位矩陣，若非方形矩陣，從左上角開始放一
eye_t=torch.eye(4,4)
print(eye_t)

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])


### 7. 常用的張量運算處理

In [13]:
x = torch.randn(3, 3)
print(x)

tensor([[-0.5094, -1.8469, -0.7771],
        [ 0.6504,  0.6050, -0.3706],
        [-1.5832,  0.4724,  0.5322]])


In [14]:
## 每行取最大值
max_value, max_idx = torch.max(x, dim=1)
print(max_value, max_idx)

tensor([-0.5094,  0.6504,  0.5322]) tensor([0, 0, 2])


In [15]:
## 每行求和
sum_x = torch.sum(x, dim=1)
print(sum_x)

tensor([-3.1334,  0.8849, -0.5785])


In [49]:
## 加法1
y = torch.randn(3, 3)
z = x + y
print(z)

tensor([[ 0.2171,  2.6940, -0.4456],
        [ 0.6608, -0.2053,  0.4663],
        [-0.5552,  1.3075, -1.1836]])


In [50]:
## 另一種加法
x.add_(y)
print(x)

tensor([[ 0.2171,  2.6940, -0.4456],
        [ 0.6608, -0.2053,  0.4663],
        [-0.5552,  1.3075, -1.1836]])


In [54]:
## 加法3
result = torch.empty(5,3)
torch.add(x,y,out=result)
print(result)

tensor([[ 0.3816,  4.3011, -1.1099],
        [ 2.0299,  0.9813,  0.2349],
        [-0.1365,  2.6820, -2.3487]])


In [22]:
## 切片
print(x)
print(x[:,1])
print(x[2,:])
print(x[:2,:2])

tensor([[-0.5094, -1.8469, -0.7771],
        [ 0.6504,  0.6050, -0.3706],
        [-1.5832,  0.4724,  0.5322]])
tensor([-1.8469,  0.6050,  0.4724])
tensor([-1.5832,  0.4724,  0.5322])
tensor([[-0.5094, -1.8469],
        [ 0.6504,  0.6050]])


In [24]:
## 改變維度
a = torch.randn(4,4)
b = a.view(16)
c = a.view(2,8)
print(a.size(),b.size(),c.size())
print(a)
print(b)
print(c)
#d = a.view(3,5)
#print(d)
e = a.view(2,2,2,2)
print(e)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])
tensor([[ 1.9814,  1.5767,  0.5532, -0.4946],
        [-0.8551, -1.5518, -0.2142,  0.1846],
        [-0.6233,  0.7324, -0.3944,  0.9039],
        [-0.3809, -0.4961, -0.1506,  0.2058]])
tensor([ 1.9814,  1.5767,  0.5532, -0.4946, -0.8551, -1.5518, -0.2142,  0.1846,
        -0.6233,  0.7324, -0.3944,  0.9039, -0.3809, -0.4961, -0.1506,  0.2058])
tensor([[ 1.9814,  1.5767,  0.5532, -0.4946, -0.8551, -1.5518, -0.2142,  0.1846],
        [-0.6233,  0.7324, -0.3944,  0.9039, -0.3809, -0.4961, -0.1506,  0.2058]])
tensor([[[[ 1.9814,  1.5767],
          [ 0.5532, -0.4946]],

         [[-0.8551, -1.5518],
          [-0.2142,  0.1846]]],


        [[[-0.6233,  0.7324],
          [-0.3944,  0.9039]],

         [[-0.3809, -0.4961],
          [-0.1506,  0.2058]]]])


### Extra - 改用cuda張量

In [64]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x,device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu",torch.double))