In [10]:
import torch

##### 生成張量時，將requires設定為True，PyTorch會對該張量做梯度計算

In [11]:
x = torch.rand(5, 5, requires_grad=True)
x

tensor([[0.6785, 0.1919, 0.0307, 0.2727, 0.4486],
        [0.3654, 0.5688, 0.9150, 0.6269, 0.6342],
        [0.4012, 0.3717, 0.2529, 0.4015, 0.5810],
        [0.4832, 0.5578, 0.4277, 0.3126, 0.0900],
        [0.0181, 0.1942, 0.0771, 0.1902, 0.9574]], requires_grad=True)

In [12]:
y = torch.rand(5, 5, requires_grad=True)
y

tensor([[0.9098, 0.0248, 0.6536, 0.8393, 0.3882],
        [0.1530, 0.5491, 0.7289, 0.5686, 0.3375],
        [0.5602, 0.0492, 0.5248, 0.9065, 0.0698],
        [0.8553, 0.1482, 0.0195, 0.9226, 0.0363],
        [0.3050, 0.6684, 0.5409, 0.4646, 0.8773]], requires_grad=True)

In [13]:
z=torch.sum(x+y)
z

tensor(22.1509, grad_fn=<SumBackward0>)

### 1. 簡單的自動求導數

In [14]:
z.backward()
print(x.grad)
print(y.grad)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


### 2. 複雜的自動求導數

In [15]:
x = torch.rand(5, 5, requires_grad=True)
y = torch.rand(5, 5, requires_grad=True)
z= x**2+y**3
z

tensor([[0.1319, 0.6425, 0.0198, 0.6689, 0.7837],
        [0.5550, 0.8676, 0.4834, 0.1259, 0.5809],
        [0.1899, 0.0538, 0.0177, 0.9240, 1.2285],
        [0.9779, 0.0647, 0.0744, 1.9799, 0.3121],
        [0.8427, 0.8504, 0.3294, 0.7494, 0.7197]], grad_fn=<AddBackward0>)

In [16]:
z.backward(torch.ones_like(x)) ## 會回傳一個跟x同樣size的單位矩陣
print(x.grad)

tensor([[0.7259, 0.2803, 0.2216, 0.1373, 0.9580],
        [0.7110, 1.8629, 0.2250, 0.7091, 1.0190],
        [0.8581, 0.2920, 0.1131, 0.2187, 1.4349],
        [1.9631, 0.0286, 0.4567, 1.9799, 0.3502],
        [0.0877, 1.6394, 0.9206, 1.7313, 0.7065]])


可以利用with torch.no_grad()<br />
來暫時禁止requires_grad=True的張量進行自動求導數<br />
常用於測試集計算準確率時<br />
可以減少記憶體使用量跟加快一點運算速度

In [17]:
with torch.no_grad():
    print((x +y*2).requires_grad)

False


### 3. Autograd 過程解析

In [18]:
dir(z) ##檢查屬性

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_priority__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__contains__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__idiv__',
 '__ilshift__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__long__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__or__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rfloordiv__',
 '__rmul__',
 '__rpow__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__se

In [19]:
## 用is_leaf確認這個張量是手動生成的，還是運算出來的
print("x.is_leaf="+str(x.is_leaf))
print("z.is_leaf="+str(z.is_leaf))

x.is_leaf=True
z.is_leaf=False


In [20]:
## grad_fn 紀錄完整的計算歷史
## AddBackward0在這裡是類型，是加法的反向傳播
z.grad_fn

In [21]:
dir(z.grad_fn) ## 檢查屬性

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_register_hook_dict',
 'metadata',
 'name',
 'next_functions',
 'register_hook',
 'requires_grad']

In [22]:
## next_functions是grad_fn的精華
z.grad_fn.next_functions

((<PowBackward0 at 0x12301f8d0>, 0), (<PowBackward0 at 0x12301fa90>, 0))

In [23]:
xg = z.grad_fn.next_functions[0][0]
dir(xg)

['__call__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_register_hook_dict',
 'metadata',
 'name',
 'next_functions',
 'register_hook',
 'requires_grad']

In [24]:
## AccumulateGrad類型是葉節點類型，也就是計算終止節點
x_leaf=xg.next_functions[0][0]
type(x_leaf)

AccumulateGrad

In [25]:
## 這個就是剛生成的x張量
x_leaf.variable

tensor([[0.3629, 0.1401, 0.1108, 0.0687, 0.4790],
        [0.3555, 0.9314, 0.1125, 0.3545, 0.5095],
        [0.4291, 0.1460, 0.0566, 0.1093, 0.7174],
        [0.9816, 0.0143, 0.2283, 0.9899, 0.1751],
        [0.0438, 0.8197, 0.4603, 0.8656, 0.3532]], requires_grad=True)

In [26]:
print("x_leaf.variable的id:"+str(id(x_leaf.variable)))
print("x的id:"+str(id(x)))

x_leaf.variable的id:4882243168
x的id:4882243168


### 4. 自定義Autograd

In [28]:
## 匯入Function
from torch.autograd.function import Function

In [31]:
# 定義一個輸入為張量，操作為乘上一個常數
# 方法必須是靜態方法，所以要加上@staticmethod 
class multiply_constant(Function):
    @staticmethod 
    def forward(ctx, tensor, constant):
        # ctx 用於保存訊息，類似self，ctx的屬性可以在backward中使用
        ctx.constant=constant
        return tensor *constant
    @staticmethod
    def backward(ctx, grad_output):
        # 回傳的參數要跟輸入的參數一樣
        # 常數的梯度是 None
        return grad_output, None

In [43]:
a = torch.rand(3,3,requires_grad=True)
b = multiply_constant.apply(a,10)
print("a:"+str(a))
print("b:"+str(b))

a:tensor([[0.8931, 0.3621, 0.6383],
        [0.6624, 0.3681, 0.3817],
        [0.9445, 0.0179, 0.1047]], requires_grad=True)
b:tensor([[8.9313, 3.6213, 6.3829],
        [6.6237, 3.6808, 3.8167],
        [9.4445, 0.1788, 1.0471]], grad_fn=<multiply_constantBackward>)


In [44]:
b.backward(torch.ones_like(a))

In [45]:
a.grad

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])