# 神經網路的資料表示法

### 1. 匯入numpy 函式庫

In [2]:
import numpy as np

### 2. 比較 0D/1D/2D/3D 張量 

In [15]:
#0D張量-純量

tensor_0d = np.array(20)     
print(tensor_0d)
print("\n"+str(tensor_0d.shape))
print("\ntensor_0d的階數為"+str(tensor_0d.ndim))

20

()

tensor_0d的階數為0


In [16]:
#1D張量-向量

tensor_1d = np.array([1, 4, 9, 16, 25])     
print(tensor_1d)
print("\n"+str(tensor_1d.shape))
print("\ntensor_1d的階數為"+str(tensor_1d.ndim))

[ 1  4  9 16 25]

(5,)

tensor_1d的階數為1


In [17]:
#2D張量-矩陣

tensor_2d = np.array([[1, 3, 5, 7, 9],    
                      [2, 6, 10, 14, 18],
                      [4, 12, 20, 28, 36],
                      [8, 24, 40, 56, 72]])    
print(tensor_2d)
print("\n"+str(tensor_2d.shape))
print("\ntensor_2d的階數為"+str(tensor_2d.ndim))

[[ 1  3  5  7  9]
 [ 2  6 10 14 18]
 [ 4 12 20 28 36]
 [ 8 24 40 56 72]]

(4, 5)

tensor_2d的階數為2


In [14]:
#3D張量

tensor_3d = np.array([[[5, 78, 2, 34, 0],         
                    [2, 8, 4, 36, 2]],
                   [[55, 8, 9, 24, 0],
                    [3, 8, 4, 326, 1]],
                   [[4, 78, 2, 134, 2],
                    [5, 21, 23, 56, 3]]])
print(tensor_3d)
print("\n"+str(tensor_3d.shape))
print("\ntensor_3d的階數為"+str(tensor_3d.ndim))

[[[  5  78   2  34   0]
  [  2   8   4  36   2]]

 [[ 55   8   9  24   0]
  [  3   8   4 326   1]]

 [[  4  78   2 134   2]
  [  5  21  23  56   3]]]

(3, 2, 5)

tensor_3d的階數為3


### 3. 調整張量改變取用影像資料量

In [23]:
from keras.datasets import mnist  
(train_images, train_labels), (test_images, test_labels) = mnist.load_data()

#只取train_images的第50-99份影像資料
my_slice = train_images[50:100]

#也可以這樣寫
#my_slice = train_images[50:100, :, :] 
#或是這樣寫
#my_slice = train_images[10:100, 0:28, 0:28]

print(my_slice.shape)

(50, 28, 28)


### 4. 資料批次 (batch) 

In [0]:
batch = train_images[:128]  #把 train_images 切片為 128 個圖像為一批 batch

In [0]:
batch = train_images[128:256]

In [0]:
# 可以修改程式的 n 值, 找到你想測試的批次量
#batch = train_images[128 * n:128 * (n + 1)]

# 張量運算

### 5. 相加、Relu

In [ ]:
import numpy as np

z = x + y  

z = np.maximum(z, 0.) 

In [0]:
def naive_add(x, y):
    assert len(x.shape) == 2  
    assert x.shape == y.shape
    
    x = x.copy()
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[i, j]
            #同等於 x[i, j] = x[i, j] + y[i, j]
    return x

In [0]:
def naive_relu(x):
    assert len(x.shape) == 2   

    x = x.copy()  #避免覆寫到輸入張量
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] = max(x[i, j], 0)
    return x

### 6. 張量擴張 (Broadcasting)

In [0]:
def naive_add_matrix_and_vector(x, y):
    assert len(x.shape) == 2  
    assert len(y.shape) == 1  
    assert x.shape[1] == y.shape[0]

    x = x.copy() 
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            x[i, j] += y[j]
    return x

In [24]:
import numpy as np

#創造隨機張量
x = np.random.random((4, 3, 32, 10))  
y = np.random.random((32, 10)) 

z = np.maximum(x, y)  # z 的 shape 同 x， y 已先被擴張了
z.shape

(4, 3, 32, 10)

### 7. 張量點積 (dot) 運算

In [4]:
import numpy as np

z = np.dot(x, y)  

In [0]:
def naive_vector_dot(x, y):
    assert len(x.shape) == 1
    assert len(y.shape) == 1  
    assert x.shape[0] == y.shape[0]
    z = 0.
    for i in range(x.shape[0]):
        z += x[i] * y[i]  # x[0]*y[0] + x[1]*y[1] + x[2]*y[2] + x[3]*y[3]….
    return z

In [0]:
import numpy as np

def naive_matrix_vector_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 1
    assert x.shape[1] == y.shape[0]

    z = np.zeros(x.shape[0])        # z 為與 x 第0軸形狀一樣, 數值為 0 的向量
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            z[i] += x[i, j] * y[j]               # z 的各元素值已被內層 for loop 填入了
    return z

In [0]:
def naive_matrix_vector_dot(x, y):      #這是一個矩陣-向量的點積運算
    z = np.zeros(x.shape[0])
    for i in range(x.shape[0]):
        z[i] = naive_vector_dot(x[i, :], y)        #內部包著一個向量-向量的點積運算
    return z

In [0]:
def naive_matrix_dot(x, y):
    assert len(x.shape) == 2
    assert len(y.shape) == 2
    assert x.shape[1] == y.shape[0]    #  x 的第 1 維的數量必須與 y 第 0 維的數量相等

    z = np.zeros((x.shape[0], y.shape[1])) 
    for i in range(x.shape[0]):
        for j in range(y.shape[1]):    #重複計算 x 各列數值與 y 各行數值
            row_x = x[i, :]
            column_y = y[:, j]
            z[i, j] = naive_vector_dot(row_x, column_y)
    return z

### 8. 張量重塑

In [5]:
x = np.array([[10, 11], 
              [20, 22],
              [30, 33]])
print(x.shape)

(3, 2)


In [35]:
x = x.reshape((6, 1))  
print(x)

[[10]
 [11]
 [20]
 [22]
 [30]
 [33]]


In [8]:
x = np.zeros((300, 20))  
x = np.transpose(x)
print(x.shape)

(20, 300)


In [9]:
x = np.array([[10, 11], 
              [20, 22],
              [30, 33]])

re_x = x.reshape((2, 3)) 
print(re_x)
tr_x = np.transpose(x)
print(tr_x)

[[10 11 20]
 [22 30 33]]
[[10 20 30]
 [11 22 33]]
